# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 17:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0003_auto_20161104_1959'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeedbackForm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('desciption', models.CharField(max_length=50)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.Course')),
            ],
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques_value', models.CharField(max_length=200)),
                ('ques_type', models.CharField(max_length=10)),
                ('feedback_form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myadmin.FeedbackForm')),
            ],
        ),
    ]
