# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-04 17:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0004_feedbackform_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='feedback_form',
            field=models.ForeignKey(null='true', on_delete=django.db.models.deletion.CASCADE, to='myadmin.FeedbackForm'),
        ),
    ]
