# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-05 16:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myadmin', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='op1',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='op2',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='op3',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='op4',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='question',
            name='op5',
            field=models.IntegerField(default=0),
        ),
    ]
