# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 10:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='mid_deadline',
            field=models.DateField(null='true'),
        ),
    ]
