# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0002_auto_20161101_1047'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='end_deadline',
            field=models.DateField(null='true'),
        ),
    ]
