# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-10-31 21:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_auto_20161031_2111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='student',
            name='student_name',
        ),
    ]
