# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 11:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0003_course_end_deadline'),
    ]

    operations = [
        migrations.CreateModel(
            name='endsemquestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='midsemquestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=1000)),
            ],
        ),
        migrations.RemoveField(
            model_name='course',
            name='mid_deadline',
        ),
        migrations.AddField(
            model_name='midsemquestion',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.course'),
        ),
        migrations.AddField(
            model_name='endsemquestion',
            name='course',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='adminApp.course'),
        ),
    ]
