# -*- coding: utf-8 -*-
# Generated by Django 1.10.2 on 2016-11-01 02:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adminApp', '0004_remove_student_student_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='endsem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('courses', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='midsem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start', models.CharField(max_length=100)),
                ('end', models.CharField(max_length=100)),
                ('courses', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='adminApp.course')),
            ],
        ),
        migrations.CreateModel(
            name='question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ques', models.CharField(max_length=1000)),
                ('endsem', models.ManyToManyField(to='adminApp.endsem')),
                ('midsem', models.ManyToManyField(to='adminApp.midsem')),
            ],
        ),
    ]
